DROP TABLE YFU_CARD_EDITOR;
DROP TABLE YFU_MEMBER;
DROP TABLE YFU_CARD_OWNER;
DROP TABLE YFU_CARD_CONTENT;
DROP TABLE YFU_CARD;

DROP SEQUENCE YFU_MEMBER_SEQ;
DROP SEQUENCE YFU_CARD_SEQ;
DROP SEQUENCE YFU_CARD_CONTENT_SEQ;

CREATE TABLE YFU_CARD (
    CARD_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
    TYPE VARCHAR2(1) NOT NULL
);

CREATE TABLE YFU_CARD_CONTENT (
    CARD_ID VARCHAR2(10) NOT NULL,
    ORDER_NUMBER NUMBER(2,0) NOT NULL,
    CONTENT NVARCHAR2(1000),
	CONSTRAINT PK_CARD_CONTENT PRIMARY KEY (CARD_ID, ORDER_NUMBER),
    CONSTRAINT FK_CARD_CONTENT_CARD
    FOREIGN KEY(CARD_ID) REFERENCES YFU_CARD(CARD_ID)
);

CREATE TABLE YFU_CARD_OWNER (
	CARD_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
	OWNER NVARCHAR2(10) NOT NULL,
	CONSTRAINT FK_CARD_OWNER_CARD
	FOREIGN KEY(CARD_ID) REFERENCES YFU_CARD(CARD_ID)
);

CREATE TABLE YFU_MEMBER (
	MEMBER_ID NUMBER(10,0) NOT NULL PRIMARY KEY,
	NAME NVARCHAR2(20) NOT NULL
);

CREATE TABLE YFU_CARD_EDITOR (
    CARD_ID VARCHAR2(10) NOT NULL,
    MEMBER_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_CARD_EDITOR PRIMARY KEY (CARD_ID, MEMBER_ID),
    CONSTRAINT FK_CARD_EDITOR_CARD
    FOREIGN KEY(CARD_ID) REFERENCES YFU_CARD(CARD_ID),
    CONSTRAINT FK_CARD_EDITOR_MEMBER
    FOREIGN KEY(MEMBER_ID) REFERENCES YFU_MEMBER(MEMBER_ID)
);

CREATE SEQUENCE YFU_MEMBER_SEQ
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE YFU_CARD_SEQ
MINVALUE 1
MAXVALUE 999
NOCYCLE
NOCACHE;

CREATE SEQUENCE YFU_CARD_CONTENT_SEQ
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE;